Repository Konkuk-KUIT/KUIT3_Web-FrontEnd, pull requests merged in 2024-03, with the labels that each got.

#13 Feat:자기소개 페이지 완성
  week1/yongchan/index.html
Labels: ChoYongChan

#3 KUIT 1주차 과제 입니다
  week1/clicelee/index.html
Labels: 이지민

#5 Feat: 자기소개 페이지 완성
  week1/woojin/index.html
Labels: 장우진

#6 1주차 과제 완료
  week1/seojin/index.html
Labels: 김서진

#7 Feat: 1강 실습 자기소개 페이지
  week1/turtlehwan/index.html
Labels: 김지환

#8 feat : 강연욱 자기소개 페이지
  week1/yeonwook/index.html
Labels: 강연욱

#9 Feat: 자기소개 페이지 완성
  week1/Seungwoo/index.html
  week1/nayeon/index.html
  week1/nayeon1/index.html
Labels: 문승우

#15 Feat:자기소개 페이지 완성
  week1/yongchan/index.html
Labels: 조용찬

#16 feat: week1 self introduction
  week1/ro-el/index.html
Labels: 정경은😛

#17 Feat: 자기소개 페이지 완성
  week1/dainn/index.html
Labels: 손다인

#18 Feat: 자기소개 페이지 완성
  week1/yeonwoo/index.html
Labels: 정연우

#21 2주차 과제
  week2/yeonwook/assets/aroundme.svg
  week2/yeonwook/assets/chat.svg
  week2/yeonwook/assets/chatting.svg
  week2/yeonwook/assets/expandArrow.svg
  week2/yeonwook/assets/heart.svg
  week2/yeonwook/assets/home.svg
  week2/yeonwook/assets/item1.svg
  week2/yeonwook/assets/item2.svg
  week2/yeonwook/assets/item3.svg
  week2/yeonwook/assets/item4.svg
  week2/yeonwook/assets/map.svg
  week2/yeonwook/assets/menu.svg
  week2/yeonwook/assets/mydanggeun.svg
  week2/yeonwook/assets/notification.svg
  week2/yeonwook/assets/plus.svg
  week2/yeonwook/assets/search.svg
  week2/yeonwook/index.css
  week2/yeonwook/reset.css
  week2/yeonwook/w2exercise.html
  week2/yeonwook/week2screenshot1.jpg
  week2/yeonwook/week2screenshot2.jpg
  week2/yeonwook/미션스크린샷1.jpg
  week2/yeonwook/미션스크린샷2.jpg
Labels: 강연욱

#22 Feat(week2): daangn page_1 clone
  week2/turtlehwan/daangn_1/assets/footer/btn-chat.svg
  week2/turtlehwan/daangn_1/assets/footer/btn-home-clicked.svg
  week2/turtlehwan/daangn_1/assets/footer/btn-nearby.svg
  week2/turtlehwan/daangn_1/assets/footer/btn-neighborhood.svg
  week2/turtlehwan/daangn_1/assets/footer/btn-plus-newpost.svg
  week2/turtlehwan/daangn_1/assets/footer/btn-profile.svg
  week2/turtlehwan/daangn_1/assets/header/btn-expand-arrow.svg
  week2/turtlehwan/daangn_1/assets/header/btn-menu.svg
  week2/turtlehwan/daangn_1/assets/header/btn-notification.svg
  week2/turtlehwan/daangn_1/assets/header/btn-search.svg
  week2/turtlehwan/daangn_1/assets/product/chat.svg
  week2/turtlehwan/daangn_1/assets/product/heart.svg
  week2/turtlehwan/daangn_1/index.css
  week2/turtlehwan/daangn_1/index.html
  week2/turtlehwan/daangn_1/reset.css
Labels: 김지환

#26 Feat: 당근 홈페이지 완성
  .vscode/launch.json
  .vscode/settings.json
  reset.css
  week2/woojin/assets/QA.svg
  week2/woojin/assets/alarm.svg
  week2/woojin/assets/chat.svg
  week2/woojin/assets/chat2.svg
  week2/woojin/assets/comment.svg
  week2/woojin/assets/dropdown.svg
  week2/woojin/assets/emotion.svg
  week2/woojin/assets/heart.svg
  week2/woojin/assets/home.svg
  week2/woojin/assets/list.svg
  week2/woojin/assets/map.svg
  week2/woojin/assets/mapicon.svg
  week2/woojin/assets/model.svg
  week2/woojin/assets/mycarrot.svg
  week2/woojin/assets/mylife.svg
  week2/woojin/assets/navchat.svg
  week2/woojin/assets/participation.svg
  week2/woojin/assets/plus.svg
  week2/woojin/assets/search.svg
  week2/woojin/assets/surrounding.svg
  week2/woojin/assets/wallet.svg
  week2/woojin/assets/wallet2.svg
  week2/woojin/index.css
  week2/woojin/index.html
  week2/woojin/index2.css
  week2/woojin/index2.html
  week2/woojin/reset.css
Labels: 장우진

#29 당근마켓 페이지 구현
  week1/leeeunbin/index.html
  week2/eunbin0325/daangn1/img/plus.png
  week2/eunbin0325/daangn1/index..html
  week2/eunbin0325/daangn1/index.css
  week2/eunbin0325/daangn1/reset.css
  week2/eunbin0325/daangn2/img/advertisement.jpg
  week2/eunbin0325/daangn2/img/chat.png
  week2/eunbin0325/daangn2/img/lost.jpg
  week2/eunbin0325/daangn2/img/lost2.jpg
  week2/eunbin0325/daangn2/img/participation.png
  week2/eunbin0325/daangn2/img/plus.png
  week2/eunbin0325/daangn2/index.html
  week2/eunbin0325/daangn2/reset.css
  week2/eunbin0325/daangn2/style.css
Labels: 이은빈

#30 feat: 당근마켓 홈 화면 클론코딩 (KUIT 3기 Web week2 미션)
  week2/jiyoung/assets/.DS_Store
  week2/jiyoung/assets/add.svg
  week2/jiyoung/assets/chat.svg
  week2/jiyoung/assets/down-chevron.svg
  week2/jiyoung/assets/heart.svg
  week2/jiyoung/assets/menu.svg
  week2/jiyoung/assets/nav/chat.svg
  week2/jiyoung/assets/nav/home.svg
  week2/jiyoung/assets/nav/news.svg
  week2/jiyoung/assets/nav/place.svg
  week2/jiyoung/assets/nav/user.svg
  week2/jiyoung/assets/notification.svg
  week2/jiyoung/assets/search.svg
  week2/jiyoung/index.css
  week2/jiyoung/index.html
  week2/jiyoung/reset.css
Labels: 문지영

#31 Feat: 2주차 미션
  week2/dainn/assets/bx:chat.svg
  week2/dainn/assets/chat.svg
  week2/dainn/assets/expand_arrow.svg
  week2/dainn/assets/heart.svg
  week2/dainn/assets/home.svg
  week2/dainn/assets/img1.jpeg
  week2/dainn/assets/menu.svg
  week2/dainn/assets/news.svg
  week2/dainn/assets/notification.svg
  week2/dainn/assets/placemarker.svg
  week2/dainn/assets/plus.svg
  week2/dainn/assets/plus_button.svg
  week2/dainn/assets/search.svg
  week2/dainn/assets/user.svg
  week2/dainn/index.css
  week2/dainn/index.html
  week2/dainn/reset.css
Labels: 손다인

#24 Feat: week2 daangn1 clone
  week1/index.html
  week2/seoyoung/assets/bx-chat.svg
  week2/seoyoung/assets/chat.svg
  week2/seoyoung/assets/down-chevron.svg
  week2/seoyoung/assets/heart.svg
  week2/seoyoung/assets/home.svg
  week2/seoyoung/assets/menu.svg
  week2/seoyoung/assets/news.svg
  week2/seoyoung/assets/notification.svg
  week2/seoyoung/assets/place.svg
  week2/seoyoung/assets/plus.svg
  week2/seoyoung/assets/search.svg
  week2/seoyoung/assets/user.svg
  week2/seoyoung/index.css
  week2/seoyoung/index.html
  week2/seoyoung/reset.css
Labels: 박서영

#27 Feat: Week2 Daangn Clone
  .gitignore
  week2/seojin/Inter/Inter-VariableFont_slnt,wght.ttf
  week2/seojin/Inter/OFL.txt
  week2/seojin/Inter/README.txt
  week2/seojin/Inter/static/Inter-Black.ttf
  week2/seojin/Inter/static/Inter-Bold.ttf
  week2/seojin/Inter/static/Inter-ExtraBold.ttf
  week2/seojin/Inter/static/Inter-ExtraLight.ttf
  week2/seojin/Inter/static/Inter-Light.ttf
  week2/seojin/Inter/static/Inter-Medium.ttf
  week2/seojin/Inter/static/Inter-Regular.ttf
  week2/seojin/Inter/static/Inter-SemiBold.ttf
  week2/seojin/Inter/static/Inter-Thin.ttf
  week2/seojin/assets/bell.svg
  week2/seojin/assets/chat.svg
  week2/seojin/assets/down-chevron.svg
  week2/seojin/assets/heart.svg
  week2/seojin/assets/home.svg
  week2/seojin/assets/kebab.svg
  week2/seojin/assets/message.svg
  week2/seojin/assets/news.svg
  week2/seojin/assets/placeMarder.svg
  week2/seojin/assets/plus.svg
  week2/seojin/assets/search.svg
  week2/seojin/assets/user.svg
  week2/seojin/index.css
  week2/seojin/index.html
  week2/seojin/reset.css
Labels: 김서진

#36 feat: 당근마켓 클론코딩
  week2/.vscode/settings.json
  week2/clicelee/assets/floating-icon-actionButton.svg
  week2/clicelee/assets/header-icon-alarm.svg
  week2/clicelee/assets/header-icon-list.svg
  week2/clicelee/assets/header-icon-search.svg
  week2/clicelee/assets/item-icon-chats.svg
  week2/clicelee/assets/item-icon-liked.svg
  week2/clicelee/assets/nav-icon-aroundMe.svg
  week2/clicelee/assets/nav-icon-chats.svg
  week2/clicelee/assets/nav-icon-home.svg
  week2/clicelee/assets/nav-icon-profile.svg
  week2/clicelee/assets/nav-icon-villageLife.svg
  week2/clicelee/index.css
  week2/clicelee/index.html
  week2/clicelee/reset.css
Labels: 이지민🎲

#25 feat: 당근마켓 페이지 구현
  week2/yeonwoo/미션/assets/airpod.jpg
  week2/yeonwoo/미션/assets/chat.svg
  week2/yeonwoo/미션/assets/chat2.svg
  week2/yeonwoo/미션/assets/eheqhrl.svg
  week2/yeonwoo/미션/assets/heart.svg
  week2/yeonwoo/미션/assets/home.svg
  week2/yeonwoo/미션/assets/marker.svg
  week2/yeonwoo/미션/assets/news.svg
  week2/yeonwoo/미션/assets/plus_back.svg
  week2/yeonwoo/미션/assets/tkawlckd.svg
  week2/yeonwoo/미션/assets/under-chevron.svg
  week2/yeonwoo/미션/assets/user.svg
  week2/yeonwoo/미션/assets/whd.svg
  week2/yeonwoo/미션/index.css
  week2/yeonwoo/미션/index.html
  week2/yeonwoo/미션/reset.css
  week2/yeonwoo/실습/assets/airpod.jpg
  week2/yeonwoo/실습/assets/headphone.jpg
  week2/yeonwoo/실습/assets/heart.svg
  week2/yeonwoo/실습/assets/home.svg
  week2/yeonwoo/실습/assets/kebab.svg
  week2/yeonwoo/실습/assets/left-chevron.svg
  week2/yeonwoo/실습/assets/nintendo.jpg
  week2/yeonwoo/실습/assets/reset.css
  week2/yeonwoo/실습/assets/right-chevron.svg
  week2/yeonwoo/실습/assets/share.svg
  week2/yeonwoo/실습/index.css
  week2/yeonwoo/실습/index.html
  week2/yeonwoo/실습/reset.css
Labels: 정연우

#38 Feat:2주차 미션 제출_폴더 ChoYongChan 폴더 생
  week2/ChoYongChan_W2/assets/chat3.svg
  week2/ChoYongChan_W2/assets/chatting.svg
  week2/ChoYongChan_W2/assets/expanded_arrow.svg
  week2/ChoYongChan_W2/assets/heart11.svg
  week2/ChoYongChan_W2/assets/heart2.svg
  week2/ChoYongChan_W2/assets/home.svg
  week2/ChoYongChan_W2/assets/home_1.svg
  week2/ChoYongChan_W2/assets/kebab.svg
  week2/ChoYongChan_W2/assets/left_shevron.svg
  week2/ChoYongChan_W2/assets/menu.svg
  week2/ChoYongChan_W2/assets/my_carrot.svg
  week2/ChoYongChan_W2/assets/near_me.svg
  week2/ChoYongChan_W2/assets/notification.svg
  week2/ChoYongChan_W2/assets/plus.svg
  week2/ChoYongChan_W2/assets/right_shevron.svg
  week2/ChoYongChan_W2/assets/search.svg
  week2/ChoYongChan_W2/assets/share.svg
  week2/ChoYongChan_W2/assets/town_life.svg
  week2/ChoYongChan_W2/index.css
  week2/ChoYongChan_W2/index.html
  week2/ChoYongChan_W2/reset.css
Labels: 조용찬
