Repository Konkuk-KUIT/KUIT3_Web-FrontEnd, pull requests merged in 2024-04, with the labels that each got.

#41 2주차 과제 폴더 수정
  week2/seungwoo/assets/around.svg
  week2/seungwoo/assets/bell.svg
  week2/seungwoo/assets/chatting.svg
  week2/seungwoo/assets/comment.svg
  week2/seungwoo/assets/down-chevron.svg
  week2/seungwoo/assets/home.svg
  week2/seungwoo/assets/like.svg
  week2/seungwoo/assets/living.svg
  week2/seungwoo/assets/mycarrot.svg
  week2/seungwoo/assets/plus_icon.svg
  week2/seungwoo/assets/search.svg
  week2/seungwoo/assets/three.svg
  week2/seungwoo/index.css
  week2/seungwoo/index.html
  week2/seungwoo/reset.css
Labels: 문승우

#28 당근마켓 페이지 완성
  week2/assets/around.svg
  week2/assets/bell.svg
  week2/assets/chatting.svg
  week2/assets/comment.svg
  week2/assets/down-chevron.svg
  week2/assets/home.svg
  week2/assets/like.svg
  week2/assets/living.svg
  week2/assets/mycarrot.svg
  week2/assets/plus_icon.svg
  week2/assets/search.svg
  week2/assets/three.svg
  week2/index.css
  week2/index.html
  week2/reset.css
Labels: 문승우

#35 Feat: 당근마켓 페이지 2주차 미션
  week2/yoonseo/assets/Chat.svg
  week2/yoonseo/assets/Expand Arrow.svg
  week2/yoonseo/assets/Frame 21.svg
  week2/yoonseo/assets/Home.svg
  week2/yoonseo/assets/Menu.svg
  week2/yoonseo/assets/News.svg
  week2/yoonseo/assets/Notification.svg
  week2/yoonseo/assets/Place Marker.svg
  week2/yoonseo/assets/Rectangle 2 (1).svg
  week2/yoonseo/assets/Rectangle 2 (2).svg
  week2/yoonseo/assets/Rectangle 2 (3).svg
  week2/yoonseo/assets/Rectangle 2 (4).svg
  week2/yoonseo/assets/Rectangle 2.svg
  week2/yoonseo/assets/Search.svg
  week2/yoonseo/assets/User.svg
  week2/yoonseo/assets/ant-design_heart-outlined.svg
  week2/yoonseo/assets/bx_chat.svg
  week2/yoonseo/reset.css
  week2/yoonseo/week2.css
  week2/yoonseo/week2.html
Labels: 김윤서

#39 3주차 미션
  week3/yeonwook/todo/app.js
  week3/yeonwook/todo/db.json
  week3/yeonwook/todo/index.css
  week3/yeonwook/todo/index.html
Labels: 강연욱

#40 Feat(week3): TodoList update
  week3/turtlehwan/babel/index.js
  week3/turtlehwan/babel/package-lock.json
  week3/turtlehwan/babel/package.json
  week3/turtlehwan/es6/index.js
  week3/turtlehwan/todo/app.js
  week3/turtlehwan/todo/db.json
  week3/turtlehwan/todo/index.css
  week3/turtlehwan/todo/index.html
Labels: 김지환🐢

#42 feat: todo list update 기능 구현
  week3/ro-el/app.js
  week3/ro-el/db.json
  week3/ro-el/todo.css
  week3/ro-el/todo.html
Labels: 정경은😛

#43 3주차 과제 완성
  week3/woojin/babel/index.js
  week3/woojin/babel/package-lock.json
  week3/woojin/babel/package.json
  week3/woojin/es6/index.js
  week3/woojin/todo/app.js
  week3/woojin/todo/db.json
  week3/woojin/todo/index.css
  week3/woojin/todo/index.html
Labels: 장우진

#44 3주차 미션
  week3/eunbin0402/todo/app.js
  week3/eunbin0402/todo/db.json
  week3/eunbin0402/todo/index.html
  week3/eunbin0402/todo/style.css
Labels: 이은빈

#45 3주차 미션 제출
  week3/yeonwoo/todo/app.js
  week3/yeonwoo/todo/db.json
  week3/yeonwoo/todo/index.css
  week3/yeonwoo/todo/index.html
Labels: 정연우

#46 3주차 미션 제출
  week3/dainn/todo/app.js
  week3/dainn/todo/db.json
  week3/dainn/todo/index.css
  week3/dainn/todo/index.html
Labels: 손다인

#48 3주차 미션 제출
  week1/seoyoung/index.html
  week3/seoyoung/app.js
  week3/seoyoung/db.json
  week3/seoyoung/index.css
  week3/seoyoung/index.html
Labels: 박서영

#50 3주차 미션 제출
  week3/ChoYongChan_W3/app.js
  week3/ChoYongChan_W3/db.json
  week3/ChoYongChan_W3/index.css
  week3/ChoYongChan_W3/index.html
Labels: 조용찬

#51 3주차 미션
  week3/clicelee/todo/app.js
  week3/clicelee/todo/db.json
  week3/clicelee/todo/index.css
  week3/clicelee/todo/index.html
Labels: 이지민🎲

#52 feat: 3주차 미션 제출
  week3/seojin/app.js
  week3/seojin/db.json
  week3/seojin/index.css
  week3/seojin/index.html
Labels: 김서진

#47 Feat: 3주차 미션 제출
  week3/yoonseo/app.js
  week3/yoonseo/db.json
  week3/yoonseo/index.css
  week3/yoonseo/index.html
Labels: 김윤서

#55 Feat : 4주차 과제제출
  week4/yeonwook/todo/app.js
  week4/yeonwook/todo/app.ts
  week4/yeonwook/todo/db.json
  week4/yeonwook/todo/index.css
  week4/yeonwook/todo/index.html
  week4/yeonwook/todo/tsconfig.json
Labels: 강연욱

#56 Feat(week4): Refactoring JS -> TS with async, await
  week4/turtlehwan/todo/app.js
  week4/turtlehwan/todo/app.ts
  week4/turtlehwan/todo/db.json
  week4/turtlehwan/todo/index.css
  week4/turtlehwan/todo/index.html
  week4/turtlehwan/todo/tsconfig.json
Labels: 김지환🐢

#58 feat: week4 mission - js to ts
  week4/ro-el/app.js
  week4/ro-el/app.ts
  week4/ro-el/db.json
  week4/ro-el/todo.css
  week4/ro-el/todo.html
  week4/ro-el/tsconfig.json
Labels: 정경은😛

#60 Feat: 4주차 미션 제출
  week4/todo/app.js
  week4/todo/app.ts
  week4/todo/db.json
  week4/todo/index.css
  week4/todo/index.html
  week4/todo/tsconfig.json
Labels: 조용찬

#61 4주차 과제 제출
  week4/woojin/babel/index.js
  week4/woojin/babel/package-lock.json
  week4/woojin/babel/package.json
  week4/woojin/es6/index.js
  week4/woojin/todo/app.js
  week4/woojin/todo/app.ts
  week4/woojin/todo/db.json
  week4/woojin/todo/index.css
  week4/woojin/todo/index.html
  week4/woojin/todo/tsconfig.json
Labels: 장우진

#64 Feat: 4주차 미션
  week4/dainn/app.js
  week4/dainn/app.ts
  week4/dainn/db.json
  week4/dainn/index.css
  week4/dainn/index.html
  week4/dainn/package.json
  week4/dainn/tsconfig.json
Labels: 손다인

#66 4주차 미션 제출
  week4/seoyoung/app.js
  week4/seoyoung/app.ts
  week4/seoyoung/db.json
  week4/seoyoung/index.css
  week4/seoyoung/index.html
  week4/seoyoung/tsconfig.json
Labels: 박서영

#67 feat: 4주차 미션
  package-lock.json
  package.json
  tsconfig.json
  week4/seojin/app.js
  week4/seojin/app.ts
  week4/seojin/db.json
  week4/seojin/index.css
  week4/seojin/index.html
  week4/seojin/tsconfig.json
Labels: 김서진
