Repository Konkuk-KUIT/KUIT3_Web-FrontEnd, pull requests merged in 2024-05, with the labels that each got.

#59 4주차 미션
  .gitignore
  package-lock.json
  week3/eunbin0402/todo/app.js
  week3/eunbin0402/todo/db.json
  week4/eunbin0409/app.js
  week4/eunbin0409/app.ts
  week4/eunbin0409/tsconfig.json
  week5/leeeunbin/.gitignore
  week5/leeeunbin/README.md
  week5/leeeunbin/package-lock.json
  week5/leeeunbin/package.json
  week5/leeeunbin/public/index.html
  week5/leeeunbin/src/App.js
  week5/leeeunbin/src/Todo.js
  week5/leeeunbin/src/index.js
  week5/leeeunbin/src/todoData.json
Labels: 이은빈

#71 5차시 과제제출
  week5/yeonwook/package-lock.json
  week5/yeonwook/package.json
  week5/yeonwook/public/index.html
  week5/yeonwook/src/App.js
  week5/yeonwook/src/Completed.jsx
  week5/yeonwook/src/POverFive.jsx
  week5/yeonwook/src/Todo.js
  week5/yeonwook/src/index.js
  week5/yeonwook/src/todoData.json
Labels: 강연욱

#72 Feat(week5): React 조건부, 배열 렌더링
  week5/turtlehwan/package-lock.json
  week5/turtlehwan/package.json
  week5/turtlehwan/public/index.html
  week5/turtlehwan/src/App.js
  week5/turtlehwan/src/Todo.js
  week5/turtlehwan/src/index.js
  week5/turtlehwan/src/todoData.json
Labels: 김지환🐢

#74 feat: week5 미션 구현
  .gitignore
  week5/ro-el/package-lock.json
  week5/ro-el/package.json
  week5/ro-el/public/index.css
  week5/ro-el/public/index.html
  week5/ro-el/src/App.js
  week5/ro-el/src/Todo.js
  week5/ro-el/src/index.js
  week5/ro-el/src/todoData.json
  week5/ro-el/src/강의실습.js
  week5/ro-el/todoData.json
Labels: 정경은😛

#77 feat: 조건부렌더링 사용해 map 2개 생성 후 출력 (KUIT 3기 Web week5 미션)
  .DS_Store
  week3/.DS_Store
  week3/jiyoung/app.js
  week3/jiyoung/db.json
  week3/jiyoung/index.css
  week3/jiyoung/index.html
  week5/jiyoung/package-lock.json
  week5/jiyoung/package.json
  week5/jiyoung/public/index.html
  week5/jiyoung/src/App.js
  week5/jiyoung/src/Todo.js
  week5/jiyoung/src/index.js
  week5/jiyoung/src/todoData.json
Labels: 문지영

#78 Feat: 5주차 미션
  week5/yoonseo/.gitignore
  week5/yoonseo/package-lock.json
  week5/yoonseo/package.json
  week5/yoonseo/public/index.html
  week5/yoonseo/src/App.js
  week5/yoonseo/src/Todo.js
  week5/yoonseo/src/index.js
  week5/yoonseo/src/todoData.json
Labels: 김윤서

#79 feat: week5 미션 구현
  week5/seojin/package-lock.json
  week5/seojin/package.json
  week5/seojin/public/index.html
  week5/seojin/src/App.css
  week5/seojin/src/App.js
  week5/seojin/src/Todo.js
  week5/seojin/src/index.js
  week5/seojin/src/todoData.json
Labels: 김서진

#86 Feat: 5주차 과제 제출
  week5/seoyoung/package-lock.json
  week5/seoyoung/package.json
  week5/seoyoung/public/index.html
  week5/seoyoung/src/App.js
  week5/seoyoung/src/Todo.js
  week5/seoyoung/src/index.js
  week5/seoyoung/src/todoData.json
Labels: 박서영

#20 Feat: 자기소개 페이지 완성1
  .vscode/launch.json
  .vscode/settings.json
  reset.css
  week1/seongyou/index.html
  week2/jinho1011/clone/assets/heart.svg
  week2/jinho1011/clone/assets/home.svg
  week2/jinho1011/clone/assets/kebab.svg
  week2/jinho1011/clone/assets/left-chevron copy.svg
  week2/jinho1011/clone/assets/left-chevron.svg
  week2/jinho1011/clone/assets/right-chevron.svg
  week2/jinho1011/clone/assets/share.svg
  week2/jinho1011/clone/index.css
  week2/jinho1011/clone/index.html
  week2/jinho1011/clone/reset.css
  week2/seongyou/assets/chat.svg
  week2/seongyou/assets/expand-arrow.svg
  week2/seongyou/assets/heart.svg
  week2/seongyou/assets/home.svg
  week2/seongyou/assets/kebab.svg
  week2/seongyou/assets/left-chevron.svg
  week2/seongyou/assets/menu.svg
  week2/seongyou/assets/notification.svg
  week2/seongyou/assets/right-chevron.svg
  week2/seongyou/assets/search.svg
  week2/seongyou/assets/share.svg
  week2/seongyou/index.css
  week2/seongyou/index.html
  week2/seongyou/reset.css
  week3/jinho1011/todo/app.js
  week5/seongyou/public/index.html
  week5/seongyou/src/App.js
  week5/seongyou/src/Todo.js
  week5/seongyou/src/index.js
  week5/seongyou/src/todoData.json
Labels: 김성유

#89 Feat(week6): ProductRow 컴포넌트 상품 삭제 기능 & Test Case
  week5/turtlehwan/.gitignore
  week6/turtlehwan/.gitignore
  week6/turtlehwan/README.md
  week6/turtlehwan/jest.config.js
  week6/turtlehwan/package-lock.json
  week6/turtlehwan/package.json
  week6/turtlehwan/public/favicon.ico
  week6/turtlehwan/public/index.html
  week6/turtlehwan/public/logo192.png
  week6/turtlehwan/public/logo512.png
  week6/turtlehwan/public/manifest.json
  week6/turtlehwan/public/robots.txt
  week6/turtlehwan/src/App.spec.tsx
  week6/turtlehwan/src/App.tsx
  week6/turtlehwan/src/components/FilterableProductTable.tsx
  week6/turtlehwan/src/components/InputBar.tsx
  week6/turtlehwan/src/components/ProductCategoryRow.tsx
  week6/turtlehwan/src/components/ProductRow.tsx
  week6/turtlehwan/src/components/ProductTable.tsx
  week6/turtlehwan/src/components/SearchBar.tsx
  week6/turtlehwan/src/index.tsx
  week6/turtlehwan/src/react-app-env.d.ts
  week6/turtlehwan/tsconfig.json
Labels: 김지환🐢

#91 6주차 과제제출
  week6/yeonwook/.gitignore
  week6/yeonwook/README.md
  week6/yeonwook/jest.config.js
  week6/yeonwook/package-lock.json
  week6/yeonwook/package.json
  week6/yeonwook/public/favicon.ico
  week6/yeonwook/public/index.html
  week6/yeonwook/public/logo192.png
  week6/yeonwook/public/logo512.png
  week6/yeonwook/public/manifest.json
  week6/yeonwook/public/robots.txt
  week6/yeonwook/src/App.spec.tsx
  week6/yeonwook/src/App.tsx
  week6/yeonwook/src/components/FilterableProductTable.tsx
  week6/yeonwook/src/components/InputBar.tsx
  week6/yeonwook/src/components/ProductCategoryRow.tsx
  week6/yeonwook/src/components/ProductRow.tsx
  week6/yeonwook/src/components/ProductTable.tsx
  week6/yeonwook/src/components/SearchBar.tsx
  week6/yeonwook/src/index.tsx
  week6/yeonwook/src/react-app-env.d.ts
  week6/yeonwook/tsconfig.json
Labels: 강연욱

#95 Feat: 6주차 미션
  week6/yoonseo/.gitignore
  week6/yoonseo/README.md
  week6/yoonseo/jest.config.js
  week6/yoonseo/package-lock.json
  week6/yoonseo/package.json
  week6/yoonseo/public/favicon.ico
  week6/yoonseo/public/index.html
  week6/yoonseo/public/logo192.png
  week6/yoonseo/public/logo512.png
  week6/yoonseo/public/manifest.json
  week6/yoonseo/public/robots.txt
  week6/yoonseo/src/App.spec.tsx
  week6/yoonseo/src/App.tsx
  week6/yoonseo/src/components/FilterableProductTable.tsx
  week6/yoonseo/src/components/InputBar.tsx
  week6/yoonseo/src/components/ProductCategoryRow.tsx
  week6/yoonseo/src/components/ProductRow.tsx
  week6/yoonseo/src/components/ProductTable.tsx
  week6/yoonseo/src/components/SearchBar.tsx
  week6/yoonseo/src/index.tsx
  week6/yoonseo/src/react-app-env.d.ts
  week6/yoonseo/tsconfig.json
Labels: 김윤서

#97 6주차 미션
  week6/clicelee/.gitignore
  week6/clicelee/README.md
  week6/clicelee/jest.config.js
  week6/clicelee/package-lock.json
  week6/clicelee/package.json
  week6/clicelee/public/favicon.ico
  week6/clicelee/public/index.html
  week6/clicelee/public/logo192.png
  week6/clicelee/public/logo512.png
  week6/clicelee/public/manifest.json
  week6/clicelee/public/robots.txt
  week6/clicelee/src/App.spec.tsx
  week6/clicelee/src/App.tsx
  week6/clicelee/src/components/FilterableProductTable.tsx
  week6/clicelee/src/components/InputBar.tsx
  week6/clicelee/src/components/ProductCategoryRow.tsx
  week6/clicelee/src/components/ProductRow.tsx
  week6/clicelee/src/components/ProductTable.tsx
  week6/clicelee/src/components/SearchBar.tsx
  week6/clicelee/src/index.tsx
  week6/clicelee/src/react-app-env.d.ts
  week6/clicelee/tsconfig.json
Labels: 이지민🎲

#98 Feat 6주차 미션
  week6/seoyoung/.gitignore
  week6/seoyoung/README.md
  week6/seoyoung/jest.config.js
  week6/seoyoung/package-lock.json
  week6/seoyoung/package.json
  week6/seoyoung/public/favicon.ico
  week6/seoyoung/public/index.html
  week6/seoyoung/public/logo192.png
  week6/seoyoung/public/logo512.png
  week6/seoyoung/public/manifest.json
  week6/seoyoung/public/robots.txt
  week6/seoyoung/src/App.spec.tsx
  week6/seoyoung/src/App.tsx
  week6/seoyoung/src/components/FilterableProductTable.tsx
  week6/seoyoung/src/components/InputBar.tsx
  week6/seoyoung/src/components/ProductCategoryRow.tsx
  week6/seoyoung/src/components/ProductRow.tsx
  week6/seoyoung/src/components/ProductTable.tsx
  week6/seoyoung/src/components/SearchBar.tsx
  week6/seoyoung/src/index.tsx
  week6/seoyoung/src/react-app-env.d.ts
  week6/seoyoung/tsconfig.json
Labels: 박서영

#75 Feat:5주차 미션,6주차 미션
  week5/.gitignore
  week5/package-lock.json
  week5/package.json
  week5/public/index.html
  week5/src/App.js
  week5/src/Todo.js
  week5/src/index.js
  week5/src/todoData.json
  week6/.gitignore
  week6/README.md
  week6/jest.config.js
  week6/package-lock.json
  week6/package.json
  week6/public/favicon.ico
  week6/public/index.html
  week6/public/logo192.png
  week6/public/logo512.png
  week6/public/manifest.json
  week6/public/robots.txt
  week6/src/App.spec.tsx
  week6/src/App.tsx
  week6/src/components/FilterableProductTable.tsx
  week6/src/components/InputBar.tsx
  week6/src/components/ProductCategoryRow.tsx
  week6/src/components/ProductRow.tsx
  week6/src/components/ProductTable.tsx
  week6/src/components/SearchBar.tsx
  week6/src/index.tsx
  week6/src/react-app-env.d.ts
  week6/tsconfig.json
Labels: 조용찬

#94 6주차 과제
  .gitignore
  week5/dainn/package.json
  week5/dainn/public/index.html
  week5/dainn/src/App.js
  week5/dainn/src/Todo.js
  week5/dainn/src/index.js
  week5/dainn/src/todoData.json
  week6/dainn/README.md
  week6/dainn/jest.config.js
  week6/dainn/package-lock.json
  week6/dainn/package.json
  week6/dainn/public/favicon.ico
  week6/dainn/public/index.html
  week6/dainn/public/logo192.png
  week6/dainn/public/logo512.png
  week6/dainn/public/manifest.json
  week6/dainn/public/robots.txt
  week6/dainn/src/App.spec.tsx
  week6/dainn/src/App.tsx
  week6/dainn/src/components/FilterableProductTable.tsx
  week6/dainn/src/components/InputBar.tsx
  week6/dainn/src/components/ProductCategoryRow.tsx
  week6/dainn/src/components/ProductRow.tsx
  week6/dainn/src/components/ProductTable.tsx
  week6/dainn/src/components/SearchBar.tsx
  week6/dainn/src/index.tsx
  week6/dainn/src/react-app-env.d.ts
  week6/dainn/tsconfig.json
Labels: 손다인

#96 feat. 6주차 미션
  week6/leeeunbin/.gitignore
  week6/leeeunbin/README.md
  week6/leeeunbin/jest.config.js
  week6/leeeunbin/package-lock.json
  week6/leeeunbin/package.json
  week6/leeeunbin/public/favicon.ico
  week6/leeeunbin/public/index.html
  week6/leeeunbin/public/logo192.png
  week6/leeeunbin/public/logo512.png
  week6/leeeunbin/public/manifest.json
  week6/leeeunbin/public/robots.txt
  week6/leeeunbin/src/App.spec.tsx
  week6/leeeunbin/src/App.tsx
  week6/leeeunbin/src/components/EditModal.tsx
  week6/leeeunbin/src/components/FilterableProductsTable.tsx
  week6/leeeunbin/src/components/InputBar.tsx
  week6/leeeunbin/src/components/ProductCategoryRow.tsx
  week6/leeeunbin/src/components/ProductRow.tsx
  week6/leeeunbin/src/components/ProductTable.tsx
  week6/leeeunbin/src/components/SearchBar.tsx
  week6/leeeunbin/src/components/index.tsx
  week6/leeeunbin/src/data-access/index.tsx
  week6/leeeunbin/src/data-access/product.tsx
  week6/leeeunbin/src/index.tsx
  week6/leeeunbin/src/react-app-env.d.ts
  week6/leeeunbin/tsconfig.json
Labels: question, 이은빈

#104 7주차 미션
  .vscode/settings.json
  week7/dainn/package-lock.json
  week7/dainn/package.json
  week7/dainn/public/favicon.ico
  week7/dainn/public/index.html
  week7/dainn/public/logo192.png
  week7/dainn/public/logo512.png
  week7/dainn/public/manifest.json
  week7/dainn/public/robots.txt
  week7/dainn/src/App.js
  week7/dainn/src/components/Header.jsx
  week7/dainn/src/db.js
  week7/dainn/src/index.js
  week7/dainn/src/routes/Detail.jsx
  week7/dainn/src/routes/Home.jsx
  week7/dainn/src/routes/Router.jsx
  week7/dainn/src/routes/User.jsx
Labels: 손다인

#105 7주차과제제출
  week7/yeonwook/.gitignore
  week7/yeonwook/README.md
  week7/yeonwook/package-lock.json
  week7/yeonwook/package.json
  week7/yeonwook/public/favicon.ico
  week7/yeonwook/public/index.html
  week7/yeonwook/public/logo192.png
  week7/yeonwook/public/logo512.png
  week7/yeonwook/public/manifest.json
  week7/yeonwook/public/robots.txt
  week7/yeonwook/src/App.js
  week7/yeonwook/src/assets/logo192.png
  week7/yeonwook/src/components/Header.jsx
  week7/yeonwook/src/db.js
  week7/yeonwook/src/index.js
  week7/yeonwook/src/routes/Detail.jsx
  week7/yeonwook/src/routes/Home.jsx
  week7/yeonwook/src/routes/Router.jsx
  week7/yeonwook/src/routes/User.jsx
Labels: 강연욱

#106 feat: 7주차 미션 완료
  week7/seojin/.gitignore
  week7/seojin/README.md
  week7/seojin/package-lock.json
  week7/seojin/package.json
  week7/seojin/public/favicon.ico
  week7/seojin/public/index.html
  week7/seojin/public/logo192.png
  week7/seojin/public/logo512.png
  week7/seojin/public/manifest.json
  week7/seojin/public/robots.txt
  week7/seojin/src/App.css
  week7/seojin/src/App.js
  week7/seojin/src/components/Header.js
  week7/seojin/src/db.js
  week7/seojin/src/index.js
  week7/seojin/src/pages/Detail.js
  week7/seojin/src/pages/Home.js
  week7/seojin/src/pages/MyPage.js
  week7/seojin/src/pages/User.js
  week7/seojin/src/styles/Header.css
Labels: 김서진

#107 Feat: 7주차 미션
  week7/seoyoung/.gitignore
  week7/seoyoung/README.md
  week7/seoyoung/package-lock.json
  week7/seoyoung/package.json
  week7/seoyoung/public/favicon.ico
  week7/seoyoung/public/index.html
  week7/seoyoung/public/logo192.png
  week7/seoyoung/public/logo512.png
  week7/seoyoung/public/manifest.json
  week7/seoyoung/public/robots.txt
  week7/seoyoung/src/App.js
  week7/seoyoung/src/components/Header.jsx
  week7/seoyoung/src/db.js
  week7/seoyoung/src/index.js
  week7/seoyoung/src/routes/Detail.jsx
  week7/seoyoung/src/routes/Home.jsx
  week7/seoyoung/src/routes/Router.jsx
  week7/seoyoung/src/routes/User.jsx
Labels: 박서영

#108 feat: 7주차 미션 제출
  week7/yeonwoo/.gitignore
  week7/yeonwoo/README.md
  week7/yeonwoo/package-lock.json
  week7/yeonwoo/package.json
  week7/yeonwoo/public/favicon.ico
  week7/yeonwoo/public/index.html
  week7/yeonwoo/public/logo192.png
  week7/yeonwoo/public/logo512.png
  week7/yeonwoo/public/manifest.json
  week7/yeonwoo/public/robots.txt
  week7/yeonwoo/src/App.tsx
  week7/yeonwoo/src/components/GoBack.jsx
  week7/yeonwoo/src/components/Header.jsx
  week7/yeonwoo/src/db.js
  week7/yeonwoo/src/index.tsx
  week7/yeonwoo/src/routes/Detail.jsx
  week7/yeonwoo/src/routes/Home.jsx
  week7/yeonwoo/src/routes/Router.jsx
  week7/yeonwoo/src/routes/User.jsx
  week7/yeonwoo/tsconfig.json
Labels: 정연우

#112 7주차 미션 완료
  week6/seungwoo/src/components/ProductRow.tsx
  week7/seungwoo/.gitignore
  week7/seungwoo/README.md
  week7/seungwoo/package-lock.json
  week7/seungwoo/package.json
  week7/seungwoo/public/favicon.ico
  week7/seungwoo/public/index.html
  week7/seungwoo/public/logo192.png
  week7/seungwoo/public/logo512.png
  week7/seungwoo/public/manifest.json
  week7/seungwoo/public/robots.txt
  week7/seungwoo/src/App.js
  week7/seungwoo/src/components/Header.jsx
  week7/seungwoo/src/db.js
  week7/seungwoo/src/index.js
  week7/seungwoo/src/routes/Detail.jsx
  week7/seungwoo/src/routes/Home.jsx
  week7/seungwoo/src/routes/Router.jsx
  week7/seungwoo/src/routes/User.jsx
Labels: 문승우

#113 7주차 미션
  week7/leeeunbin/.gitignore
  week7/leeeunbin/README.md
  week7/leeeunbin/package-lock.json
  week7/leeeunbin/package.json
  week7/leeeunbin/public/favicon.ico
  week7/leeeunbin/public/image/header.jpg
  week7/leeeunbin/public/image/user1.webp
  week7/leeeunbin/public/image/user2.webp
  week7/leeeunbin/public/image/user3.jpg
  week7/leeeunbin/public/index.html
  week7/leeeunbin/public/logo192.png
  week7/leeeunbin/public/logo512.png
  week7/leeeunbin/public/manifest.json
  week7/leeeunbin/public/robots.txt
  week7/leeeunbin/src/App.js
  week7/leeeunbin/src/components/Header.jsx
  week7/leeeunbin/src/db.js
  week7/leeeunbin/src/index.js
  week7/leeeunbin/src/routes/Detail.jsx
  week7/leeeunbin/src/routes/Home.jsx
  week7/leeeunbin/src/routes/Login.jsx
  week7/leeeunbin/src/routes/Router.jsx
  week7/leeeunbin/src/routes/User.jsx
Labels: 이은빈

#116 7주차 미션 (브랜치 변경)
  week7/leeeunbin/.gitignore
  week7/leeeunbin/README.md
  week7/leeeunbin/package-lock.json
  week7/leeeunbin/package.json
  week7/leeeunbin/public/favicon.ico
  week7/leeeunbin/public/image/header.jpg
  week7/leeeunbin/public/image/user1.webp
  week7/leeeunbin/public/image/user2.webp
  week7/leeeunbin/public/image/user3.jpg
  week7/leeeunbin/public/index.html
  week7/leeeunbin/public/logo192.png
  week7/leeeunbin/public/logo512.png
  week7/leeeunbin/public/manifest.json
  week7/leeeunbin/public/robots.txt
  week7/leeeunbin/src/App.js
  week7/leeeunbin/src/components/Header.jsx
  week7/leeeunbin/src/db.js
  week7/leeeunbin/src/index.js
  week7/leeeunbin/src/routes/Detail.jsx
  week7/leeeunbin/src/routes/Home.jsx
  week7/leeeunbin/src/routes/Login.jsx
  week7/leeeunbin/src/routes/Router.jsx
  week7/leeeunbin/src/routes/User.jsx
Labels: 이은빈

#114 Feat(week7): 주어진 코드 스타일링 하기
  week7/turtlehwan/.gitignore
  week7/turtlehwan/README.md
  week7/turtlehwan/package-lock.json
  week7/turtlehwan/package.json
  week7/turtlehwan/public/favicon.ico
  week7/turtlehwan/public/index.html
  week7/turtlehwan/public/logo192.png
  week7/turtlehwan/public/logo512.png
  week7/turtlehwan/public/manifest.json
  week7/turtlehwan/public/robots.txt
  week7/turtlehwan/src/App.js
  week7/turtlehwan/src/components/Header.jsx
  week7/turtlehwan/src/db.js
  week7/turtlehwan/src/index.js
  week7/turtlehwan/src/routes/Detail.jsx
  week7/turtlehwan/src/routes/Home.jsx
  week7/turtlehwan/src/routes/Router.jsx
  week7/turtlehwan/src/routes/User.jsx
  week7/turtlehwan/src/styles/Card.styles.jsx
Labels: 김지환🐢

#115 feat: 홈/상세 페이지 스타일링 (KUIT 3기 Web week7 미션)
  week7/jiyoung/.gitignore
  week7/jiyoung/README.md
  week7/jiyoung/package-lock.json
  week7/jiyoung/package.json
  week7/jiyoung/public/favicon.ico
  week7/jiyoung/public/index.html
  week7/jiyoung/public/logo192.png
  week7/jiyoung/public/logo512.png
  week7/jiyoung/public/manifest.json
  week7/jiyoung/public/robots.txt
  week7/jiyoung/src/App.js
  week7/jiyoung/src/components/Header.jsx
  week7/jiyoung/src/db.js
  week7/jiyoung/src/index.js
  week7/jiyoung/src/routes/Detail.jsx
  week7/jiyoung/src/routes/Home.jsx
  week7/jiyoung/src/routes/Router.jsx
  week7/jiyoung/src/routes/User.jsx
Labels: 문지영

#117 Seongyou
  package-lock.json
  package.json
  week6/seongyou/.gitignore
  week6/seongyou/README.md
  week6/seongyou/package-lock.json
  week6/seongyou/package.json
  week6/seongyou/public/favicon.ico
  week6/seongyou/public/index.html
  week6/seongyou/public/logo192.png
  week6/seongyou/public/logo512.png
  week6/seongyou/public/manifest.json
  week6/seongyou/public/robots.txt
  week6/seongyou/src/App.tsx
  week6/seongyou/src/component/FilterableProductTable.tsx
  week6/seongyou/src/component/InputBar.tsx
  week6/seongyou/src/component/ProductCategoryRow.tsx
  week6/seongyou/src/component/ProductRow.tsx
  week6/seongyou/src/component/ProductTable.tsx
  week6/seongyou/src/component/SearchBar.tsx
  week6/seongyou/src/index.tsx
  week6/seongyou/src/react-app-env.d.ts
  week6/seongyou/tsconfig.json
  week7/seongyou/.gitignore
  week7/seongyou/README.md
  week7/seongyou/package-lock.json
  week7/seongyou/package.json
  week7/seongyou/public/favicon.ico
  week7/seongyou/public/index.html
  week7/seongyou/public/logo192.png
  week7/seongyou/public/logo512.png
  week7/seongyou/public/manifest.json
  week7/seongyou/public/robots.txt
  week7/seongyou/src/App.js
  week7/seongyou/src/components/Header.jsx
  week7/seongyou/src/db.js
  week7/seongyou/src/index.js
  week7/seongyou/src/routes/Detail.jsx
  week7/seongyou/src/routes/Home.jsx
  week7/seongyou/src/routes/Login.jsx
  week7/seongyou/src/routes/Router.jsx
  week7/seongyou/src/routes/User.jsx
Labels: 김성유

#118 feat: week8 미션
  week8/ro-el/.gitignore
  week8/ro-el/README.md
  week8/ro-el/package-lock.json
  week8/ro-el/package.json
  week8/ro-el/public/favicon.ico
  week8/ro-el/public/index.html
  week8/ro-el/public/logo192.png
  week8/ro-el/public/logo512.png
  week8/ro-el/public/manifest.json
  week8/ro-el/public/robots.txt
  week8/ro-el/src/App.jsx
  week8/ro-el/src/assets/circle-default-img.svg
  week8/ro-el/src/assets/circle-exclamation-mark.svg
  week8/ro-el/src/assets/left-chevron.svg
  week8/ro-el/src/assets/rectangle-default-img.svg
  week8/ro-el/src/assets/right-chevron.svg
  week8/ro-el/src/assets/star-gray.svg
  week8/ro-el/src/assets/star-yellow.svg
  week8/ro-el/src/components/MenuItem/MenuItem.jsx
  week8/ro-el/src/components/MenuItem/MenuItem.styles.jsx
  week8/ro-el/src/components/OrderBar/OrderBar.jsx
  week8/ro-el/src/components/OrderBar/OrderBar.styles.jsx
  week8/ro-el/src/components/OrderItem/OrderItem.jsx
  week8/ro-el/src/components/OrderItem/OrderItem.styles.jsx
  week8/ro-el/src/components/StoreItem/StoreItem.jsx
  week8/ro-el/src/components/StoreItem/StoreItem.styles.jsx
  week8/ro-el/src/fonts/Pretendard-Black.woff
  week8/ro-el/src/fonts/Pretendard-Bold.woff
  week8/ro-el/src/fonts/Pretendard-ExtraBold.woff
  week8/ro-el/src/fonts/Pretendard-ExtraLight.woff
  week8/ro-el/src/fonts/Pretendard-Light.woff
  week8/ro-el/src/fonts/Pretendard-Medium.woff
  week8/ro-el/src/fonts/Pretendard-Regular.woff
  week8/ro-el/src/fonts/Pretendard-SemiBold.woff
  week8/ro-el/src/fonts/Pretendard-Thin.woff
  week8/ro-el/src/fonts/fonts.js
  week8/ro-el/src/index.js
  week8/ro-el/src/models/stores.js
  week8/ro-el/src/pages/Cart/Cart.jsx
  week8/ro-el/src/pages/Cart/Cart.styles.jsx
  week8/ro-el/src/pages/Home/Home.jsx
  week8/ro-el/src/pages/Store/Store.jsx
  week8/ro-el/src/pages/Store/Store.styles.jsx
  week8/ro-el/src/pages/Stores/Stores.jsx
  week8/ro-el/src/pages/Stores/Stores.styles.jsx
  week8/ro-el/src/pages/index.jsx
  week8/ro-el/src/store/useCartStore.js
Labels: 정경은😛

#121 feat: 8주차 미션
  week3/.DS_Store
  week8/dainn/README.md
  week8/dainn/package-lock.json
  week8/dainn/package.json
  week8/dainn/public/favicon.ico
  week8/dainn/public/index.html
  week8/dainn/public/logo192.png
  week8/dainn/public/logo512.png
  week8/dainn/public/manifest.json
  week8/dainn/public/robots.txt
  week8/dainn/src/App.jsx
  week8/dainn/src/components/MenuItem/MenuItem.jsx
  week8/dainn/src/components/MenuItem/MenuItem.styles.jsx
  week8/dainn/src/components/OrderBar/OrderBar.jsx
  week8/dainn/src/components/OrderBar/OrderBar.styles.jsx
  week8/dainn/src/components/OrderMenu/OrderMenu.jsx
  week8/dainn/src/components/StoreInfo/StoreInfo.jsx
  week8/dainn/src/components/StoreList/StoreList.jsx
  week8/dainn/src/index.js
  week8/dainn/src/models/stores.js
  week8/dainn/src/pages/Cart/Cart.jsx
  week8/dainn/src/pages/Home/Home.jsx
  week8/dainn/src/pages/Store/Store.jsx
  week8/dainn/src/pages/Stores/Stores.jsx
  week8/dainn/src/pages/index.jsx
  week8/dainn/src/store/useCartStore.js
Labels: 손다인

#124 feat: 8주차 과제
  week8/seojin/.gitignore
  week8/seojin/README.md
  week8/seojin/package-lock.json
  week8/seojin/package.json
  week8/seojin/public/favicon.ico
  week8/seojin/public/index.html
  week8/seojin/public/manifest.json
  week8/seojin/public/robots.txt
  week8/seojin/src/App.css
  week8/seojin/src/App.js
  week8/seojin/src/assets/Frame.png
  week8/seojin/src/assets/Star.png
  week8/seojin/src/assets/Vector.png
  week8/seojin/src/assets/alert.svg
  week8/seojin/src/assets/greyStar.png
  week8/seojin/src/assets/leftShevron.svg
  week8/seojin/src/assets/plus.svg
  week8/seojin/src/assets/thumbnail.png
  week8/seojin/src/components/MenuItem/MenuItem.styles.jsx
  week8/seojin/src/components/MenuItem/Menuitem.jsx
  week8/seojin/src/components/OrderBar/OrderBar.jsx
  week8/seojin/src/components/OrderBar/OrderBar.module.css
  week8/seojin/src/components/OrderItem/OrderItem.jsx
  week8/seojin/src/components/StoreItem/StoreItem.jsx
  week8/seojin/src/index.css
  week8/seojin/src/index.js
  week8/seojin/src/models/stores.js
  week8/seojin/src/pages/Cart.jsx
  week8/seojin/src/pages/Home.jsx
  week8/seojin/src/pages/Store.jsx
  week8/seojin/src/pages/Stores.jsx
  week8/seojin/src/pages/index.jsx
  week8/seojin/src/store/useCart.js
  week8/seojin/src/styles/Cart_styles.module.css
  week8/seojin/src/styles/OrderItem_styles.module.css
  week8/seojin/src/styles/Store_styles.module.css
  week8/seojin/src/styles/Stores_styles.module.css
Labels: 김서진

#125 Feat:Week8Mission
  week8/yeonwook/mission/.gitignore
  week8/yeonwook/mission/README.md
  week8/yeonwook/mission/package-lock.json
  week8/yeonwook/mission/package.json
  week8/yeonwook/mission/public/favicon.ico
  week8/yeonwook/mission/public/index.html
  week8/yeonwook/mission/public/logo192.png
  week8/yeonwook/mission/public/logo512.png
  week8/yeonwook/mission/public/manifest.json
  week8/yeonwook/mission/public/robots.txt
  week8/yeonwook/mission/src/App.jsx
  week8/yeonwook/mission/src/assets/fonts/pretendard.css
  week8/yeonwook/mission/src/assets/fonts/woff/Pretendard-Black.woff
  week8/yeonwook/mission/src/assets/fonts/woff/Pretendard-Bold.woff
  week8/yeonwook/mission/src/assets/fonts/woff/Pretendard-ExtraBold.woff
  week8/yeonwook/mission/src/assets/fonts/woff/Pretendard-ExtraLight.woff
  week8/yeonwook/mission/src/assets/fonts/woff/Pretendard-Light.woff
  week8/yeonwook/mission/src/assets/fonts/woff/Pretendard-Medium.woff
  week8/yeonwook/mission/src/assets/fonts/woff/Pretendard-Regular.woff
  week8/yeonwook/mission/src/assets/fonts/woff/Pretendard-SemiBold.woff
  week8/yeonwook/mission/src/assets/fonts/woff/Pretendard-Thin.woff
  week8/yeonwook/mission/src/assets/fonts/woff2/Pretendard-Black.woff2
  week8/yeonwook/mission/src/assets/fonts/woff2/Pretendard-Bold.woff2
  week8/yeonwook/mission/src/assets/fonts/woff2/Pretendard-ExtraBold.woff2
  week8/yeonwook/mission/src/assets/fonts/woff2/Pretendard-ExtraLight.woff2
  week8/yeonwook/mission/src/assets/fonts/woff2/Pretendard-Light.woff2
  week8/yeonwook/mission/src/assets/fonts/woff2/Pretendard-Medium.woff2
  week8/yeonwook/mission/src/assets/fonts/woff2/Pretendard-Regular.woff2
  week8/yeonwook/mission/src/assets/fonts/woff2/Pretendard-SemiBold.woff2
  week8/yeonwook/mission/src/assets/fonts/woff2/Pretendard-Thin.woff2
  week8/yeonwook/mission/src/assets/img/alert.svg
  week8/yeonwook/mission/src/assets/img/backarrow.svg
  week8/yeonwook/mission/src/assets/img/detailarrow.svg
  week8/yeonwook/mission/src/assets/img/grayStar.svg
  week8/yeonwook/mission/src/assets/img/image.png
  week8/yeonwook/mission/src/assets/img/imageCircle.svg
  week8/yeonwook/mission/src/assets/img/star.svg
  week8/yeonwook/mission/src/components/MenuItem/MenuItem.jsx
  week8/yeonwook/mission/src/components/MenuItem/MenuItem.styles.jsx
  week8/yeonwook/mission/src/components/OrderBar/OrderBar.jsx
  week8/yeonwook/mission/src/components/OrderBar/OrderBar.styles.jsx
  week8/yeonwook/mission/src/components/SelectedMenu/SelectedMenu.jsx
  week8/yeonwook/mission/src/components/SelectedMenu/SelectedMenu.styles.jsx
  week8/yeonwook/mission/src/index.js
  week8/yeonwook/mission/src/models/stores.js
  week8/yeonwook/mission/src/pages/Cart/Cart.jsx
  week8/yeonwook/mission/src/pages/Cart/Cart.styles.jsx
  week8/yeonwook/mission/src/pages/Home/Home.jsx
  week8/yeonwook/mission/src/pages/Store/Store.jsx
  week8/yeonwook/mission/src/pages/Store/Store.styles.jsx
  week8/yeonwook/mission/src/pages/Stores/Stores.jsx
  week8/yeonwook/mission/src/pages/Stores/Stores.styles.jsx
  week8/yeonwook/mission/src/pages/index.jsx
  week8/yeonwook/mission/src/store/useCartStore.js
Labels: 강연욱

#126 feat. 8주차 과제
  week8/leeeunbin/.gitignore
  week8/leeeunbin/README.md
  week8/leeeunbin/package-lock.json
  week8/leeeunbin/package.json
  week8/leeeunbin/public/favicon.ico
  week8/leeeunbin/public/image/burger.png
  week8/leeeunbin/public/image/chicken.png
  week8/leeeunbin/public/image/coffee.png
  week8/leeeunbin/public/image/dessert.png
  week8/leeeunbin/public/image/japanese.png
  week8/leeeunbin/public/image/korean.png
  week8/leeeunbin/public/image/pasta.png
  week8/leeeunbin/public/image/pizza.png
  week8/leeeunbin/public/image/salad.png
  week8/leeeunbin/public/image/sandwich.png
  week8/leeeunbin/public/image/sushi.png
  week8/leeeunbin/public/index.html
  week8/leeeunbin/public/logo192.png
  week8/leeeunbin/public/logo512.png
  week8/leeeunbin/public/manifest.json
  week8/leeeunbin/public/robots.txt
  week8/leeeunbin/src/App.jsx
  week8/leeeunbin/src/components/MenuItem/MenuItem.jsx
  week8/leeeunbin/src/components/MenuItem/MenuItem.scss
  week8/leeeunbin/src/components/OrderBar/OrderBar.jsx
  week8/leeeunbin/src/components/OrderBar/OrderBar.scss
  week8/leeeunbin/src/components/StoreItem/StoreItem.jsx
  week8/leeeunbin/src/components/StoreItem/StoreItem.scss
  week8/leeeunbin/src/components/header/Header.jsx
  week8/leeeunbin/src/components/header/Header.scss
  week8/leeeunbin/src/data-access/cart/actions.js
  week8/leeeunbin/src/data-access/cart/reducers.js
  week8/leeeunbin/src/data-access/menu/actions.js
  week8/leeeunbin/src/data-access/menu/reducers.js
  week8/leeeunbin/src/data-access/order/actions.js
  week8/leeeunbin/src/data-access/order/reducers.js
  week8/leeeunbin/src/data-access/store.js
  week8/leeeunbin/src/data-access/user/actions.js
  week8/leeeunbin/src/data-access/user/reducers.js
  week8/leeeunbin/src/database/customerDB.js
  week8/leeeunbin/src/database/storeDB.js
  week8/leeeunbin/src/index.js
  week8/leeeunbin/src/models/stores.js
  week8/leeeunbin/src/pages/AppRouter.jsx
  week8/leeeunbin/src/pages/Cart/Cart.jsx
  week8/leeeunbin/src/pages/Cart/Cart.scss
  week8/leeeunbin/src/pages/Home/Home.jsx
  week8/leeeunbin/src/pages/Home/Home.scss
  week8/leeeunbin/src/pages/Mypage/Mypage.jsx
  week8/leeeunbin/src/pages/Mypage/Mypage.scss
  week8/leeeunbin/src/pages/Order/Order.jsx
  week8/leeeunbin/src/pages/Order/Order.scss
  week8/leeeunbin/src/pages/Store/Store.jsx
  week8/leeeunbin/src/pages/Store/Store.scss
  week8/leeeunbin/src/pages/Stores/Stores.jsx
  week8/leeeunbin/src/pages/Stores/Stores.scss
  week8/leeeunbin/src/pages/index.jsx
  week8/leeeunbin/src/store/useCartStore.js
Labels: 이은빈

#127 Feat:8주차 미션
  week8/YongChan/mission/.gitignore
  week8/YongChan/mission/package-lock.json
  week8/YongChan/mission/package.json
  week8/YongChan/mission/public/PriceAlert.svg
  week8/YongChan/mission/public/backarrow.svg
  week8/YongChan/mission/public/favicon.ico
  week8/YongChan/mission/public/index.html
  week8/YongChan/mission/public/logo192.png
  week8/YongChan/mission/public/logo512.png
  week8/YongChan/mission/public/manifest.json
  week8/YongChan/mission/public/robots.txt
  week8/YongChan/mission/src/App.jsx
  week8/YongChan/mission/src/components/MenuItem/MenuItem.jsx
  week8/YongChan/mission/src/components/MenuItem/MenuItem.styles.jsx
  week8/YongChan/mission/src/components/OrderBar/OrderBar.jsx
  week8/YongChan/mission/src/components/OrderBar/OrderBar.styles.jsx
  week8/YongChan/mission/src/index.js
  week8/YongChan/mission/src/models/stores.js
  week8/YongChan/mission/src/pages/Cart/Cart.jsx
  week8/YongChan/mission/src/pages/Home/Home.jsx
  week8/YongChan/mission/src/pages/Store/Store.jsx
  week8/YongChan/mission/src/pages/Stores/Stores.jsx
  week8/YongChan/mission/src/pages/index.jsx
  week8/YongChan/mission/src/store/useCartStore.js
Labels: 조용찬

#128 feat: 8주차 미션
  week6/yeonwoo/src/components/ProductCategoryRow.tsx
  week8/yeonwoo/.gitignore
  week8/yeonwoo/README.md
  week8/yeonwoo/package-lock.json
  week8/yeonwoo/package.json
  week8/yeonwoo/public/favicon.ico
  week8/yeonwoo/public/index.html
  week8/yeonwoo/public/logo192.png
  week8/yeonwoo/public/logo512.png
  week8/yeonwoo/public/manifest.json
  week8/yeonwoo/public/robots.txt
  week8/yeonwoo/src/App.jsx
  week8/yeonwoo/src/assets/circle-exclamation-mark.svg
  week8/yeonwoo/src/assets/image.svg
  week8/yeonwoo/src/assets/left-chevron.svg
  week8/yeonwoo/src/assets/menuImage.svg
  week8/yeonwoo/src/assets/plus.svg
  week8/yeonwoo/src/assets/star.svg
  week8/yeonwoo/src/assets/yellowStar.svg
  week8/yeonwoo/src/components/MenuItem.jsx
  week8/yeonwoo/src/components/OrderBar.jsx
  week8/yeonwoo/src/index.tsx
  week8/yeonwoo/src/models/stores.js
  week8/yeonwoo/src/pages/Cart.jsx
  week8/yeonwoo/src/pages/Router.jsx
  week8/yeonwoo/src/pages/Store.jsx
  week8/yeonwoo/src/pages/Stores.jsx
  week8/yeonwoo/src/store/useCartStore.js
Labels: 정연우

#129 feat: 8주차 미션 제출
  week8/jiyoung/.gitignore
  week8/jiyoung/README.md
  week8/jiyoung/package-lock.json
  week8/jiyoung/package.json
  week8/jiyoung/public/favicon.ico
  week8/jiyoung/public/index.html
  week8/jiyoung/public/logo192.png
  week8/jiyoung/public/logo512.png
  week8/jiyoung/public/manifest.json
  week8/jiyoung/public/robots.txt
  week8/jiyoung/src/App.jsx
  week8/jiyoung/src/components/MenuItem/MenuItem.jsx
  week8/jiyoung/src/components/MenuItem/MenuItem.styles.jsx
  week8/jiyoung/src/components/OrderBar/OrderBar.jsx
  week8/jiyoung/src/components/OrderBar/OrderBar.styles.jsx
  week8/jiyoung/src/components/StoreItem/StoreItem.jsx
  week8/jiyoung/src/index.js
  week8/jiyoung/src/models/stores.js
  week8/jiyoung/src/pages/Cart/Cart.jsx
  week8/jiyoung/src/pages/Cart/Cart.styles.jsx
  week8/jiyoung/src/pages/Home/Home.jsx
  week8/jiyoung/src/pages/Store/Store.jsx
  week8/jiyoung/src/pages/Store/Store.styles.jsx
  week8/jiyoung/src/pages/Stores/Stores.jsx
  week8/jiyoung/src/pages/Stores/Stores.styles.jsx
  week8/jiyoung/src/pages/index.jsx
  week8/jiyoung/src/store/useCartStore.js
Labels: 문지영

#130 week8 미션 제출
  week8/seongyou/.gitignore
  week8/seongyou/README.md
  week8/seongyou/package-lock.json
  week8/seongyou/package.json
  week8/seongyou/public/favicon.ico
  week8/seongyou/public/index.html
  week8/seongyou/public/logo192.png
  week8/seongyou/public/logo512.png
  week8/seongyou/public/manifest.json
  week8/seongyou/public/robots.txt
  week8/seongyou/src/App.jsx
  week8/seongyou/src/components/MenuItem/MenuItem.jsx
  week8/seongyou/src/components/MenuItem/MenuItem.styles.jsx
  week8/seongyou/src/components/OrderBar/OrderBar.jsx
  week8/seongyou/src/components/OrderBar/OrderBar.styles.jsx
  week8/seongyou/src/index.js
  week8/seongyou/src/models/stores.js
  week8/seongyou/src/pages/Cart/Cart.jsx
  week8/seongyou/src/pages/Home/Home.jsx
  week8/seongyou/src/pages/Store/Store.jsx
  week8/seongyou/src/pages/Stores/Stores.jsx
  week8/seongyou/src/pages/index.jsx
  week8/seongyou/src/routes.jsx
  week8/seongyou/src/star.svg
  week8/seongyou/src/store/useCartStore.js
Labels: 김성유

#131 8주차 과제 제출
  week8/clicelee_2/mission/.gitignore
  week8/clicelee_2/mission/README.md
  week8/clicelee_2/mission/package-lock.json
  week8/clicelee_2/mission/package.json
  week8/clicelee_2/mission/postcss.config.js
  week8/clicelee_2/mission/public/favicon.ico
  week8/clicelee_2/mission/public/index.html
  week8/clicelee_2/mission/public/logo192.png
  week8/clicelee_2/mission/public/logo512.png
  week8/clicelee_2/mission/public/manifest.json
  week8/clicelee_2/mission/public/robots.txt
  week8/clicelee_2/mission/src/App.jsx
  week8/clicelee_2/mission/src/components/MenuItem/MenuItem.jsx
  week8/clicelee_2/mission/src/components/MenuItem/MenuItem.styles.jsx
  week8/clicelee_2/mission/src/components/OrderBar/OrderBar.jsx
  week8/clicelee_2/mission/src/img/back.svg
  week8/clicelee_2/mission/src/img/box.png
  week8/clicelee_2/mission/src/index.css
  week8/clicelee_2/mission/src/index.js
  week8/clicelee_2/mission/src/models/stores.js
  week8/clicelee_2/mission/src/pages/Cart/Cart.jsx
  week8/clicelee_2/mission/src/pages/Home/Home.jsx
  week8/clicelee_2/mission/src/pages/Store/Store.jsx
  week8/clicelee_2/mission/src/pages/Stores/Stores.jsx
  week8/clicelee_2/mission/src/pages/index.jsx
  week8/clicelee_2/mission/src/store/useCartStore.js
  week8/clicelee_2/mission/tailwind.config.js
Labels: 이지민🎲
